### PR TITLE
NoDamage reorganised 

### PR DESCRIPTION
**Pull request by thedeibo**
reorganised Main.php, and added plugin.yml

### CODE REVIEW

**Comment by Driesboy** [comment]
Thanks

**Comment by Driesboy** [comment]
Will you work by gamecraft

**Comment by thedeibo** [comment]
Yeah, Sure. If you email me at my work email, deiboibbs@gmail.com, because I have a good idea for you. ( about your website )

**Comment by thedeibo** [comment]
If you are really eager to know, visit https://github.com/thedeibo/WebTheDeiboSite

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
what ideas

**Comment by thedeibo** [comment]
basically, change it to look more profesional. More easy to look at, and pleasing to the eye. 
A good example of what I can do is here ( Below. )
https://github.com/thedeibo/WebTheDeiboSite

**Comment by Driesboy** [comment]
i will use joomla
not your website, i have make the website 3 days ago 
and he is not finished yet

**Pull request merged**
